services:
  web:
    image: ghcr.io/erase-bg/bp-api-service-rust:v0.1
    container_name: bp-api-service-rust
    network_mode: host
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - /var/www/public/app.erasebg.org/media/:/var/www/public/app.erasebg.org/media/

  db:
    image: postgres:15
    container_name: postgres_db_erasebg
    environment:
      POSTGRES_USER: erasebg
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: erasebg
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql_erasebg/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U erasebg"]
      interval: 5s
      timeout: 10s
      retries: 5
